# Generated by Django 4.2.14 on 2024-08-12 14:12

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0009_post_featured_image'),
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='artist_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='artists.post'),
        ),
        migrations.AddField(
            model_name='songs',
            name='song_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='songs',
            name='song_video_url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
