# Generated by Django 4.2.14 on 2024-08-12 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0010_remove_post_updated_on'),
        ('songs', '0003_alter_songs_options_songs_author_songs_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='artist_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='song_posts', to='artists.post'),
        ),
    ]
