# Generated by Django 4.2.14 on 2024-08-13 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('songs', '0004_alter_songs_artist_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='songs',
            old_name='content',
            new_name='description',
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs_commenter', to=settings.AUTH_USER_MODEL)),
                ('songs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_comments', to='songs.songs')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
