# Generated by Django 4.2.14 on 2024-08-12 23:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0010_remove_post_updated_on'),
        ('gigs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gigs',
            name='content',
        ),
        migrations.AddField(
            model_name='gigs',
            name='artist_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gigs_posts', to='artists.post'),
        ),
        migrations.AddField(
            model_name='gigs',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='gigs',
            name='date_of_gig',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='gigs',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gigs',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='gigs',
            name='time_of_gig',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='gigs',
            name='venue',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
