# Generated by Django 4.2.14 on 2024-08-12 23:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0002_remove_gigs_content_gigs_artist_name_gigs_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gigs',
            name='gig_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
