# Generated by Django 4.2.14 on 2024-08-13 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gigs', '0003_gigs_gig_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='gigs',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gigs_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gigs_commenter', to=settings.AUTH_USER_MODEL)),
                ('gigs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gigs_comments', to='gigs.gigs')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
