# Generated by Django 4.2.14 on 2024-08-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0004_gigs_author_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='gigs',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
    ]
