# Generated by Django 4.2.14 on 2024-08-13 09:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0005_gigs_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='gigs',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='gigs',
            name='slug',
            field=models.SlugField(default='default-slug', max_length=200, unique=True),
        ),
    ]
