# Generated by Django 4.2.14 on 2024-08-01 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Artist',
            new_name='author',
        ),
    ]
