# Generated by Django 4.2.14 on 2024-08-08 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0005_post_about_post_artist_post_genre_alter_post_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='artist',
            new_name='artist_name',
        ),
    ]
