# Generated by Django 4.2.14 on 2024-08-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0006_rename_artist_post_artist_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
