# Generated by Django 4.2.14 on 2024-08-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0007_post_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video_url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
