# Generated by Django 4.2.14 on 2024-08-12 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0009_post_featured_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='updated_on',
        ),
    ]
